-- 사용자 메뉴관리 화면을 관리자 CMS 메뉴(콘텐츠/게시판 그룹, 90100000)에 등록한다.
-- 페이지 콘텐츠 관리(90102000)와 동일한 패턴으로 90103000 메뉴를 추가한다.
-- 재실행해도 동일한 메뉴 번호/프로그램 키를 갱신한다.

START TRANSACTION;

INSERT INTO COMTNPROGRMLIST
    (PROGRM_FILE_NM, PROGRM_STRE_PATH, PROGRM_KOREAN_NM, PROGRM_DC, URL)
VALUES
    ('SghUserMenuManage', '/admin/content/userMenu/', '사용자 메뉴관리',
     '사용자(프론트) 페이지 메뉴 등록 및 콘텐츠/게시판 연결', '/admin/content/userMenu/list.do')
ON DUPLICATE KEY UPDATE
    PROGRM_STRE_PATH = VALUES(PROGRM_STRE_PATH),
    PROGRM_KOREAN_NM = VALUES(PROGRM_KOREAN_NM),
    PROGRM_DC        = VALUES(PROGRM_DC),
    URL              = VALUES(URL);

INSERT INTO COMTNMENUINFO
    (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM)
VALUES
    ('사용자 메뉴관리', 'SghUserMenuManage', 90103000, 90100000, 3,
     '사용자 페이지 메뉴 등록 및 연결', '/', '/')
ON DUPLICATE KEY UPDATE
    MENU_NM        = VALUES(MENU_NM),
    PROGRM_FILE_NM = VALUES(PROGRM_FILE_NM),
    UPPER_MENU_NO  = VALUES(UPPER_MENU_NO),
    MENU_ORDR      = VALUES(MENU_ORDR),
    MENU_DC        = VALUES(MENU_DC);

INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_CODE, MAPNG_CREAT_ID)
SELECT 90103000, 'ROLE_ADMIN', NULL
ON DUPLICATE KEY UPDATE AUTHOR_CODE = VALUES(AUTHOR_CODE);

COMMIT;
