-- SGHCMS 사용자 페이지를 비로그인 방문자에게 공개한다.

INSERT INTO COMTNROLEINFO
    (ROLE_CODE, ROLE_NM, ROLE_PTTRN, ROLE_DC, ROLE_TY, ROLE_SORT, ROLE_CREAT_DE)
VALUES
    ('web-sghcms-public', 'SGHCMS 사용자 페이지', '\\A/user/.*\\.do.*\\Z',
     '비로그인 사용자 페이지 접근 허용', 'url', '1', SYSDATE())
ON DUPLICATE KEY UPDATE
    ROLE_NM = VALUES(ROLE_NM),
    ROLE_PTTRN = VALUES(ROLE_PTTRN),
    ROLE_DC = VALUES(ROLE_DC),
    ROLE_TY = VALUES(ROLE_TY),
    ROLE_SORT = VALUES(ROLE_SORT);

INSERT INTO COMTNAUTHORROLERELATE (AUTHOR_CODE, ROLE_CODE, CREAT_DT)
VALUES ('ROLE_ANONYMOUS', 'web-sghcms-public', SYSDATE())
ON DUPLICATE KEY UPDATE CREAT_DT = VALUES(CREAT_DT);
