-- 게시판 사용자 설정 관리 프로그램·메뉴 등록
-- "콘텐츠/게시판(90100000)" 하위 90104000 번호 사용
-- (90103000은 sghcms_user_menu_DML_mysql.sql의 사용자 메뉴관리가 이미 사용)

START TRANSACTION;

INSERT INTO COMTNPROGRMLIST
    (PROGRM_FILE_NM, PROGRM_STRE_PATH, PROGRM_KOREAN_NM, PROGRM_DC, URL)
VALUES
    ('SghBoardConfig', '/admin/board/config/', '게시판 사용자 설정',
     '게시판별 사용자 작성 허용 및 본인 글 접근 제어 설정', '/admin/board/config/list.do')
ON DUPLICATE KEY UPDATE
    PROGRM_STRE_PATH = VALUES(PROGRM_STRE_PATH),
    PROGRM_KOREAN_NM = VALUES(PROGRM_KOREAN_NM),
    PROGRM_DC        = VALUES(PROGRM_DC),
    URL              = VALUES(URL);

INSERT INTO COMTNMENUINFO
    (MENU_NM, PROGRM_FILE_NM, MENU_NO, UPPER_MENU_NO, MENU_ORDR, MENU_DC, RELATE_IMAGE_PATH, RELATE_IMAGE_NM)
VALUES
    ('게시판 사용자 설정', 'SghBoardConfig', 90104000, 90100000, 4,
     '게시판별 사용자 작성 허용 및 본인 글 접근 제어 설정', '/', '/')
ON DUPLICATE KEY UPDATE
    MENU_NM        = VALUES(MENU_NM),
    PROGRM_FILE_NM = VALUES(PROGRM_FILE_NM),
    UPPER_MENU_NO  = VALUES(UPPER_MENU_NO),
    MENU_ORDR      = VALUES(MENU_ORDR),
    MENU_DC        = VALUES(MENU_DC);

INSERT INTO COMTNMENUCREATDTLS (MENU_NO, AUTHOR_CODE, MAPNG_CREAT_ID)
VALUES (90104000, 'ROLE_ADMIN', NULL)
ON DUPLICATE KEY UPDATE AUTHOR_CODE = VALUES(AUTHOR_CODE);

COMMIT;
